### ISSUE TITLE
Grandma & Stalker

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#133]
Grandma & Stalker are not technically banned from selecting themselves (and this used to be explicitly allowed, apparently)

**Comment by Mjnstag** [comment]
i think we could allow that? Grandma could use it to keep themselves more hidden if they want (e.a. grandma added to grandma chosen channel, would need to clarify how the votes would behave in that case) and stalker could use it to get themselves the upper hand when they want to get mayor since people might think nobody was threathend, but why they would use it on themselves idk
