### ISSUE TITLE
Psychopath suggestion

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#315]
[S6G5]
> You are guaranteed to have one townsfolk, one wolf, and one solo on this list. The other two positions are fair game for anyone.

- @cryptidjayden

**Comment by venomousbirds** [comment]
We've never used it, and I don't think we should start using it. This was probably being confused with Chef. Putting anything guaranteed on this list nerfs that role, especially with solo. Psychopath working with any team makes it so its too obvious who is on which team.

**Comment by McTsts** [comment]
I think what we could do is say "1 guaranteed wolf & 1 guaranteed town" or something like that, but the guaranteed solo is pretty bad for the solo and definitely shouldn't be done IMO.

**Comment by venomousbirds** [comment]
That would mean it won't be arbitrary anymore because we have to add according to the rule "at least 1 town and 1 wolf". (I could be understanding the word arbitrary wrong though)
I don't think we should guarantee anything with the psycho list, it doesn't add much and I think it'd be easier for psycho to figure out, and it encourages psycho to go out and find out who's what alignment on the list

**Comment by McTsts** [comment]
> That would mean it won't be arbitrary anymore because we have to add according to the rule "at least 1 town and 1 wolf". (I could be understanding the word arbitrary wrong though)
> I don't think we should guarantee anything with the psycho list, it doesn't add much and I think it'd be easier for psycho to figure out, and it encourages psycho to go out and find out who's what alignment on the list

Yeah, probably arbitrary is best.
