### ISSUE TITLE
Devil: wager kill the devil

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#36]
"Using the wager to attack the Devil always fails."

Maybe we should add something to clarify that when a wager is used to kill the devil that the devil wont have an increase in souls like when attacking another player since the soul is immediately used to protect the devil.

**Comment by venomousbirds** [comment]
There's been a discussion about this a few times and I don't remember what was said, but someone mentioned devil not getting/recieving souls at all because devil can't attack itself (not using soul to protect)

**Comment by McTsts** [comment]
I'm very certain that the correct answers is that using a wager to attack the Devil fails - but only the attack.
So you can still sell your soul, but the attack fails (or it simply does not happen). This is because selling your soul and the Devil attacking a player are two separate events (the first one happens, the second one doesnt)

**Comment by McTsts** [comment]
We can clarify that though
