### ISSUE TITLE
Role Idea: Bard 2

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#375]
![image](https://user-images.githubusercontent.com/24660095/120819509-ecc19880-c553-11eb-997d-83cf5ec0761a.png)

**Comment by MrTurtleJr** [comment]
Could be merged with the current Red Riding Hood suggestion, they seem a bit similar. The only difference is really that Bard 2 only knows what happens to _one_ person, but this encompasses both Townsfolk and Wolf roles, whereas the Red Riding Hood only knows what happens by Wolf roles, but therefore gets this info reliably every night.

**Comment by McTsts** [comment]
Hm, not sure how they could be merged.

**Comment by MrTurtleJr** [comment]
I was thinking Bard 2 as a bit under-buffed and Red Riding Hood a bit too buffed? The RRH can essentially, if trusted, find out who is Wolf or not by e.g. seeing who the Psychic Wolf checked or who the Infected Wolf targeted. But I guess it really depends on how many WP and WI roles are in game (especially since many WI roles are pack-less, so the result wouldn't be as conclusive to the RRH). Meanwhile Bard 2 could go the whole game without getting _any_ info, if their chosen person is killed early or is just not targeted by a wolf.

I guess you could try to compromise behind not being too strong or too weak, somehow.

**Comment by McTsts** [comment]
I was thinking Bard 2 would probably select a different person every night

**Comment by MrTurtleJr** [comment]
Ah, that would make sense.

**Comment by McTsts** [comment]
This is actual just as confirmable as Bard

**Comment by McTsts** [comment]
Closing this suggestion due to lack of development on it. Feel free to reopen this (now or at any point in the future) if you want to further discuss/develop this idea.
