### ISSUE TITLE
Role Idea: Ballot Stuffer

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#380]
![image](https://user-images.githubusercontent.com/24660095/120828272-9efd5e00-c55c-11eb-885d-7dcd9909b870.png)

**Comment by MrTurtleJr** [comment]
I'm not sure I follow? So, this Ballot-stuffing Wolf would be able to use their ability thrice? Something tells me that they would just choose the Guardian election every time so that Townsfolk is unable to get a Reporter. I also don't get the "regardless of whether someone currently has the role" part.

**Comment by bobloy** [comment]
> I'm not sure I follow? So, this Ballot-stuffing Wolf would be able to use their ability thrice? Something tells me that they would just choose the Guardian election every time so that Townsfolk is unable to get a Reporter. 

Yes, wolf would have 3 uses. But they could only pick guardian once, mayor once, and reporter once.

> I also don't get the "regardless of whether someone currently has the role" part.
They would be able to pick mayor even if there is already a mayor, causing a mayor reelection.

**Comment by McTsts** [comment]
They can force an election for every role once, so they can force one Guardian election.

**Comment by MrTurtleJr** [comment]
I'm not sure I like that aspect, because I fear every game with this Wolf would start on a Guardian. Then if the Wolves can kill the Guardian, the Townsfolk are stuck electing Guardian after Guardian, a role which is worse than Mayor in the early-game. I guess the role could be used as a rather strong Wolf Power role, but I feel that electing a Reporter would almost be impossible with this role in game, especially if it plays their actions correctly.

I liked the re-election part, though.

**Comment by McTsts** [comment]
I'm not sure what you mean? They'd only have the Guardian election once. However just forcing a re-election once in the game or something like that might be better?

**Comment by McTsts** [comment]
Could even be: After Night 1, in one night the XX may force a re-election of any elected role.

**Comment by MrTurtleJr** [comment]
> I'm not sure what you mean? They'd only have the Guardian election once. However just forcing a re-election once in the game or something like that might be better?

Imagine if this Wolf chooses the Guardian election night 1. Then, when a Guardian has been elected, the Wolves can kill this Guardian. Then the Wolf can refrain from using their ability and this process repeats. Even if we get a Runner as Guardian, the Townsfolk would be able to vote for a Mayor at best - who could then be killed again or the Wolf could then force a Mayor re-election. 

This is of course a rather specific scenario, but it would be effective in giving Townsfolk the weakest electable role in the beginning of the game and severely sabotaging them (mostly based on that Guardian is only needed when Wolves/Solos outnumber Townsfolk and therefore is useless for the first few nights).

> Could even be: After Night 1, in one night the XX may force a re-election of any elected role.

I like this suggestion, since I'm assuming a re-election is only possible if the role has already been elected? In which case a Wolf majority (or even with a tie between Wolves and Townsfolk) could attempt to re-elect a Mayor and gain voting majority.

**Comment by McTsts** [comment]
> Imagine if this Wolf chooses the Guardian election night 1. Then, when a Guardian has been elected, the Wolves can kill this Guardian. Then the Wolf can refrain from using their ability and this process repeats. Even if we get a Runner as Guardian, the Townsfolk would be able to vote for a Mayor at best - who could then be killed again or the Wolf could then force a Mayor re-election.

The next election would just be Mayor? 

> I like this suggestion, since I'm assuming a re-election is only possible if the role has already been elected? In which case a Wolf majority (or even with a tie between Wolves and Townsfolk) could attempt to re-elect a Mayor and gain voting majority.

Yes, it would be more of a role that unelects somebody, though if it starts a re-election I assume the person would remain elected until that election concludes.

**Comment by MrTurtleJr** [comment]
> The next election would just be Mayor?

I meant the difficulty level to get to a Reporter election, which is a huge tool for town, would increase drastically, which is why I prefer the other idea better.

**Comment by bobloy** [comment]
> I meant the difficulty level to get to a Reporter election, which is a huge tool for town, would increase drastically, which is why I prefer the other idea better.

I think this role will often function as delaying the reporter, but I like to think it will also be used to strategically get wolves the guardian early or something.

**Comment by MrTurtleJr** [comment]
I see that, but I still prefer the re-election that Ts suggested, to be completely honest. It feels more balanced.

**Comment by McTsts** [comment]
Not sure how necessary forcing a re-election is actually. Seems somewhat pointless?

**Comment by venomousbirds** [comment]
I don't understand the role fully, but I don't think we should stray from the usual election order (unless it's offseason). It'd be very confusing to play with

**Comment by bobloy** [comment]
If #404 is adopted, I think this role becomes a lot more interesting as written.

**Comment by McTsts** [comment]
with Guardian that strong this could be more interesting and wouldn't just be always selecting Guardian N1, however it might be very niche then, but that isn't necessarily an issue

**Comment by McTsts** [comment]
Closing this suggestion due to lack of development on it. Feel free to reopen this (now or at any point in the future) if you want to further discuss/develop this idea.
