### ISSUE TITLE
Bring back Vampire

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#460]
Vampire is one of the classic solo roles and I think we should work on balancing it in a way where we can bring it back normally. I think the best way to achieve this is to add Vampire specific roles into the game rather than nerfing vampire itself. There's already the limited role Exorcist. Perhaps Vampire could have a related UA role similar to the Plague Doctor? Being a wolf in a vampire game sucks imo, maybe also have a wolf role that interacts with underworld in some meaningful way? I think the Vampire's mechanics could be more fun if they can be made more of a focus of the game instead of a thing that kind of just happens to you.

**Comment by venomousbirds** [comment]
YES YES YES

**Comment by venomousbirds** [comment]
Adding roles to balance vampire would work
I still think Vampire on its own works great and I still don't understand why people dislike it that much.

**Comment by McTsts** [comment]
It's more about making it more enjoyable than balancing. However, the numbers also show that Vampire is *significantly* stronger than any of the other solo teams.

**Comment by venomousbirds** [comment]
That's because of killing, the vamp just recruits. Exorcist would work well with this
I wouldn't know how to make it more enjoyable because I am Vamp Fan #1 :)))))))))))))))

**Comment by McTsts** [comment]
Vampire still wins more than any of the other roles, even if its the killing roles that give them the recruits.

**Comment by venomousbirds** [comment]
That's cuz vampire straight up slaps
No but I do think a suggestion of an UA could be interesting, but we'd be getting another role that only works in a game with a specific solo
A general Unaligned that can't win when the Solo is alive might be more interesting?

**Comment by McTsts** [comment]
I'm not sure if that's needed in particular. I feel like if you're are role that wants the solo dead it'd be more interesting to play a role like PD than just a generic one.

**Comment by venomousbirds** [comment]
Maybe nerfing vampire itself so it doesn't need a very specific UA that can't be used in any other context

**Comment by ThomasRubycrust** [comment]
I'm not sure if Vampire really needs a counter UA nor can I think of a good one, the main suggestion from this issue would just be to tie the mechanics of Vampire closer into the game. Exorcist I think is already a decent step there, however the bigger issue with Vampire is role changes which the game doesn't deal very well with. Pretty much all the cases of role/alignment changes are kinda weird right now (CursedCiv, Vampire, Cupid). So I think instead of trying to think of things that work against Vampire/Solo specifically, trying to make role/alignment changes work better in general is what needs to be done? I don't have anything specific in mind right now.

**Comment by McTsts** [comment]
Categorize Vampire as a new type of role "Solo Recruitment" or something
