### ISSUE TITLE
Huntress (& Ranger) x Vampire

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#495]
The old edge case sheet lists: "If a Huntress turns Undead, their ability to kill somebody when they die is lost. They don't kill anyone by turning undead.", I do not think this is mentioned anywhere. Is this still accurate?

**Comment by McTsts** [comment]
This applies also to Ranger like in the title, but also to Mad Scientist.

**Comment by McTsts** [comment]
Reading through the edge case sheet I notice any role that has a death ability is problematic. Wolf's Cub ability would also just be wasted in a vampire game. I kind of don't like that.

**Comment by ThomasRubycrust** [comment]
> Reading through the edge case sheet I notice any role that has a death ability is problematic. Wolf's Cub ability would also just be wasted in a vampire game. I kind of don't like that.

Cub actually has a special exception, which is pretty interesting. I think the answer to this issue just is to avoid Huntress/Ranger in games with Underworld tbh. And if they do exist in the same game that's just unlucky for them if they get turned. It does add a bit of strategy because it makes it so Huntress might not want to claim as easily as normally.
