### ISSUE TITLE
Pyro Team Addition

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#526]
@12Metatron:
> I had a role idea for pyro when the wi is too strong or pyro too few, and you don't want to add more pyro.
> 
> Either disguised pyromancer or disguised wisp. They can choose a weak disguise like devil

@McTsts:
> I understand the suggestion from a balance point and I think if we can't think of anything better we should do it, but I think it's also a bit lame and I'd rather think of something more unique

@12Metatron:
> Yea, thats a vanilla version.
> If theres a more unique way to do it, would be better im sure
Maybe it should announce the disguise to the wisp/pyros
> @McTsts any ideas?

**Comment by cryptidjayden** [comment]
meh. bland. just give wisp a disguise or something.

**Comment by McTsts** [comment]
> I think a better buffed pyromancer would be something that involves powdering in some way, e.g. immune against attacks of powdered people, so I think we should still remove this and add another buffed pyro instead.

**Comment by venomousbirds** [comment]
idk man i dont read issues they're not as cool as PRs just link them if theyre duplicate 😔

**Comment by venomousbirds** [comment]
can't think of anything rn

**Comment by Shepherdwhen** [comment]
What about a role that makes powdered players appear as pyro 50% of the time

**Comment by Shepherdwhen** [comment]
Doesn't need to be exactly that but something like that

**Comment by cryptidjayden** [comment]
i think the similarity to the fp obstruction just makes that bland

**Comment by cryptidjayden** [comment]
a better pyro tertiary should have a different gimmick, rather than just the application of an obstruction

**Comment by ThomasRubycrust** [comment]
Suggestion for a new role on the Pyro team. 


**Firebug** | Solo Killing - Pyro Team
__Basics__
Each night, the Firebug may either powder one player or ward one player.
__Details__
When the Firebug wards a player, that player is protected from attacks for the night. Should anyone other than a member of the pyro team try to attack the warded player, the attack backfires, igniting the attacker as well as all powdered players. This is considered an attack, executed by the Firebug.
Powdering and warding are immediate abilities. Instead of powdering the Firebug may also unpowder.
The Firebug is a member of the pyro team and channel.
The Pyros win when they're the last ones alive.
When the last original Pyromancer dies, the Firebug turns into a Pyromancer

❌ Reject
✅ Approve


<@&584767449078169601> <@&590877989345165312>

**Comment by ThomasRubycrust** [comment]
Weird

**Comment by ThomasRubycrust** [comment]
It probably has something to do with the fact that it's a bot message in here, requires investigation.
