### ISSUE TITLE
Add Edgecase descriptions

### ISSUE THREAD

**Issue by venomousbirds** [McTsts/Werewolves-Roles#610]
> suggestion: we split our role descriptions into 3 sections: Basics/Details/Edge Cases - edge cases are things that the average person wont care about but things like "If the person a Shepherd steals from dies the vote remains", etc
a lot of our role descriptions are already horribly cluttered

>$i then puts the role without that section
> and a different command does the full description

@McTsts

**Comment by ThomasRubycrust** [comment]
I think this is how we should do it:

- `$info` gives the full description, whereas `.` gives the simplified description.
- The simplified descriptions removes the `Edge Cases` section should the role have it
- Additionally the simplified description also removes sentences surrounded by angle brackets. This would be useful because some unnecessary details arent edge cases, and must be part of the normal description, but are irrelevant to the average read.

**Comment by venomousbirds** [comment]
$help probably

**Comment by Shepherdwhen** [comment]
> What bot help message do you mean?

The message posted in information every game, it hasn't been updated in a while
