### ISSUE TITLE
Receptionist: disguises

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#69]
Is the receptionist affected by disguises? the description doesnt mention it

**Comment by venomousbirds** [comment]
It is affected by disguises like tanner and disguised fox (strong i think) so we should add that

**Comment by McTsts** [comment]
It is not affected by disguises. Disguises disguise players, not roles.

**Comment by venomousbirds** [comment]
We've let it be affected by disguises before, I remember it seeing more citizens in a game with sneaking wolf

**Comment by Mjnstag** [comment]
we probably should ask the other gms before making a final decision

**Comment by McTsts** [comment]
I'm absolutely certain the role was originally intended to be unaffected by disguises. Disguises disguise players, not roles. Since the Receptionist doesn't check players it was intended to be unaffected by disguises. 
However, it seems like it was previously changed to be affected by strong disguises and has been used like this before and it makes some sort of sense to be affected by strong disguises, so I think this should be added to the role description. In my opinion, it definitely should not be affected by weak disguises.

**Comment by Mjnstag** [comment]
yea, agree on the weak/strong disguises

**Comment by venomousbirds** [comment]
Let's add that it's affected by strong disguises. Is it also influenced by obstructions? (I think fluteplayer is listed as obstruction and I don't think that works at all with receptionist)

**Comment by Mjnstag** [comment]
good point. though we could give the number of fluteplayers for the asked role?

**Comment by McTsts** [comment]
I think we should try to use the FP obstruction more, but I'm not sure how exactly it would make much sense for this role.

**Comment by venomousbirds** [comment]
It doesn't make sense with receptionist, so let's not add it to this role

**Comment by McTsts** [comment]
👍

**Comment by McTsts** [comment]
Conclusion: Receptionist should be affected by strong disguises. While this is already default it should probably be clarified as for Recpetionist it isnt clear.

**Comment by venomousbirds** [comment]
added it but forgot to add that it fixes this issue
